#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Exocórtex.IA — Persist env vars into shell profile
# =============================================================================
# Reads .env.local (generated by setup.sh) and injects a managed source block
# into ~/.bashrc or ~/.zshrc. Secrets stay in .env.local (perm 600); the rc
# file only contains a source line — no secrets duplicated.
#
# Usage:
#   bash scripts/persist-env.sh              # detect shell, inject source block
#   bash scripts/persist-env.sh --capture    # save current env vars to .env.local first
#   bash scripts/persist-env.sh --show       # display current state
#   bash scripts/persist-env.sh --remove     # remove managed block from rc file
#   bash scripts/persist-env.sh --shell zsh  # override shell detection
#   bash scripts/persist-env.sh --env-file /path/to/.env.local
#
# Ref: https://github.com/elderbernardi/exocortex.saas
# =============================================================================

# ─── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'
log()  { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }
info() { echo -e "${CYAN}ℹ${NC} $1"; }
fail() { echo -e "${RED}✗${NC} $1"; exit 1; }

# ─── Constants ───────────────────────────────────────────────────────────────
MARKER_BEGIN="# >>> exocortex env begin >>>"
MARKER_END="# <<< exocortex env end <<<"

CAPTURE_VARS=(
  # Provedores LLM — 3 papéis (fonte única de provider/modelo/chave/endpoint)
  EXOCORTEX_DEFAULT_PROVIDER
  EXOCORTEX_DEFAULT_MODEL
  EXOCORTEX_DEFAULT_API_KEY
  EXOCORTEX_DEFAULT_BASE_URL
  EXOCORTEX_VISION_PROVIDER
  EXOCORTEX_VISION_MODEL
  EXOCORTEX_VISION_API_KEY
  EXOCORTEX_VISION_BASE_URL
  EXOCORTEX_AUX_PROVIDER
  EXOCORTEX_AUX_MODEL
  EXOCORTEX_AUX_API_KEY
  EXOCORTEX_AUX_BASE_URL
  # Serviços (não-LLM)
  TELEGRAM_BOT_TOKEN
  FIRECRAWL_API_KEY
  FIRECRAWL_BASE_URL
  CONTEXT7_API_KEY
  XAI_API_KEY
  HINDSIGHT_API_KEY
  EXOCORTEX_ENABLE_HERMES_WEBUI
  EXOCORTEX_ENABLE_HINDSIGHT
  HERMES_HOME
  EXOCORTEX_HOME
)

# ─── Args ────────────────────────────────────────────────────────────────────
ACTION="inject"
SHELL_OVERRIDE=""
ENV_FILE_OVERRIDE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --capture)  ACTION="capture" ;;
    --show)     ACTION="show" ;;
    --remove)   ACTION="remove" ;;
    --shell)    SHELL_OVERRIDE="${2:-}"; shift ;;
    --env-file) ENV_FILE_OVERRIDE="${2:-}"; shift ;;
    -h|--help)
      cat <<EOF
Usage: bash scripts/persist-env.sh [options]

Options:
  --capture         Save current env vars to .env.local before injecting
  --show            Display current state without modifying anything
  --remove          Remove the managed block from shell rc
  --shell bash|zsh  Override shell detection
  --env-file PATH   Override .env.local location
  -h, --help        Show this help

Examples:
  bash scripts/persist-env.sh
  bash scripts/persist-env.sh --capture
  bash scripts/persist-env.sh --show
  bash scripts/persist-env.sh --remove
EOF
      exit 0
      ;;
    *) fail "Flag não suportada: $1" ;;
  esac
  shift
done

# ─── Helpers ─────────────────────────────────────────────────────────────────

find_env_file() {
  if [ -n "$ENV_FILE_OVERRIDE" ]; then
    echo "$ENV_FILE_OVERRIDE"
    return
  fi
  if [ -n "${EXOCORTEX_INSTALLER_DIR:-}" ] && [ -f "$EXOCORTEX_INSTALLER_DIR/.env.local" ]; then
    echo "$EXOCORTEX_INSTALLER_DIR/.env.local"
    return
  fi
  if [ -f "$HOME/.exocortex-installer/.env.local" ]; then
    echo "$HOME/.exocortex-installer/.env.local"
    return
  fi
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if [ -f "$script_dir/../.env.local" ]; then
    echo "$script_dir/../.env.local"
    return
  fi
  echo ""
}

detect_shell() {
  if [ -n "$SHELL_OVERRIDE" ]; then
    echo "$SHELL_OVERRIDE"
    return
  fi
  case "${SHELL:-}" in
    */zsh)  echo "zsh" ;;
    */bash) echo "bash" ;;
    */fish) echo "fish" ;;
    *)      echo "bash" ;;
  esac
}

get_rc_file() {
  local shell_name="$1"
  case "$shell_name" in
    bash) echo "$HOME/.bashrc" ;;
    zsh)  echo "$HOME/.zshrc" ;;
    fish) fail "Fish não é suportado por este script. Use: set -Ux KEY value em ~/.config/fish/config.fish" ;;
    *)    fail "Shell não suportado: $shell_name" ;;
  esac
}

mask_secret() {
  local value="$1"
  if [ -z "$value" ]; then
    echo "(vazio)"
    return
  fi
  local len=${#value}
  if [ "$len" -le 8 ]; then
    echo "****"
  elif [ "$len" -le 16 ]; then
    echo "${value:0:4}...${value: -4}"
  else
    echo "${value:0:6}...${value: -4}"
  fi
}

save_to_env() {
  local file="$1" key="$2" value="$3"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    local escaped
    escaped=$(printf '%s' "$value" | sed 's/[&/\]/\\&/g')
    sed -i "s|^${key}=.*|${key}=\"${escaped}\"|" "$file"
  else
    echo "${key}=\"${value}\"" >> "$file"
  fi
}

inject_block() {
  local rc_file="$1" env_file="$2"
  if grep -q "$MARKER_BEGIN" "$rc_file" 2>/dev/null; then
    sed -i "/${MARKER_BEGIN}/,/${MARKER_END}/d" "$rc_file"
    info "Bloco anterior removido de $rc_file"
  fi
  cat >> "$rc_file" <<EOF

${MARKER_BEGIN}
# Exocórtex.IA env vars — gerado por scripts/persist-env.sh
# Secrets ficam em: $env_file (perm 600)
[ -f "$env_file" ] && set -a && source "$env_file" && set +a
${MARKER_END}
EOF
}

remove_block() {
  local rc_file="$1"
  if ! grep -q "$MARKER_BEGIN" "$rc_file" 2>/dev/null; then
    info "Nenhum bloco Exocórtex encontrado em $rc_file"
    return 0
  fi
  sed -i "/${MARKER_BEGIN}/,/${MARKER_END}/d" "$rc_file"
  log "Bloco Exocórtex removido de $rc_file"
}

show_state() {
  local rc_file="$1" env_file="$2"
  echo -e "${BOLD}Estado atual:${NC}"
  echo ""
  printf '  %-20s %s\n' "Shell rc:" "$rc_file"
  printf '  %-20s %s\n' "Env file:" "$env_file"
  if [ -f "$env_file" ]; then
    local perms
    perms=$(stat -c '%a' "$env_file" 2>/dev/null || stat -f '%Lp' "$env_file" 2>/dev/null)
    printf '  %-20s %s\n' "Env file perms:" "$perms"
  else
    printf '  %-20s %s\n' "Env file:" "(não encontrado)"
  fi
  echo ""
  if grep -q "$MARKER_BEGIN" "$rc_file" 2>/dev/null; then
    log "Bloco source presente em $rc_file"
  else
    warn "Bloco source ausente em $rc_file"
  fi
  if [ -f "$env_file" ]; then
    echo ""
    echo -e "${BOLD}Variáveis em .env.local:${NC}"
    while IFS='=' read -r key value; do
      case "$key" in
        ''|\#*) continue ;;
      esac
      value="${value%\"}"
      value="${value#\"}"
      case "$key" in
        *_KEY|*_TOKEN)
          printf '  %-26s %s\n' "$key" "$(mask_secret "$value")"
          ;;
        *)
          printf '  %-26s %s\n' "$key" "$value"
          ;;
      esac
    done < "$env_file"
  fi
}

# ─── Main ────────────────────────────────────────────────────────────────────

shell_name=$(detect_shell)
rc_file=$(get_rc_file "$shell_name")
env_file=$(find_env_file)

case "$ACTION" in
  show)
    show_state "$rc_file" "$env_file"
    ;;

  remove)
    remove_block "$rc_file"
    ;;

  capture)
    # Create .env.local if it doesn't exist
    if [ -z "$env_file" ] || [ ! -f "$env_file" ]; then
      env_file="${ENV_FILE_OVERRIDE:-$HOME/.exocortex-installer/.env.local}"
      mkdir -p "$(dirname "$env_file")"
      cat > "$env_file" <<'HEADER'
# =============================================================================
# Exocórtex.IA — Configuração Local (gerada por persist-env.sh)
# =============================================================================
HEADER
      chmod 600 "$env_file"
      log "Criado: $env_file"
    fi

    info "Capturando env vars do shell atual..."
    captured=0
    for var in "${CAPTURE_VARS[@]}"; do
      value="${!var:-}"
      if [ -n "$value" ]; then
        save_to_env "$env_file" "$var" "$value"
        case "$var" in
          *_KEY|*_TOKEN) printf '  %-26s %s\n' "$var" "$(mask_secret "$value")" ;;
          *)             printf '  %-26s %s\n' "$var" "$value" ;;
        esac
        captured=$((captured + 1))
      fi
    done

    if [ "$captured" -eq 0 ]; then
      warn "Nenhuma variável encontrada no shell atual."
      fail "Defina as env vars antes de rodar --capture, ou use o modo default para injetar o source block de um .env.local existente."
    fi
    log "$captured variável(eis) capturada(s) em $env_file"

    if [ ! -f "$rc_file" ]; then
      touch "$rc_file"
      log "Criado: $rc_file"
    fi
    inject_block "$rc_file" "$env_file"
    log "Source block injetado em $rc_file"
    echo ""
    info "Para ativar agora: source $rc_file"
    info "Novos terminais carregarão as vars automaticamente."
    ;;

  inject)
    if [ -z "$env_file" ] || [ ! -f "$env_file" ]; then
      fail ".env.local não encontrado. Execute o setup primeiro, ou use --capture para criar a partir das env vars atuais."
    fi

    if [ ! -f "$rc_file" ]; then
      touch "$rc_file"
      log "Criado: $rc_file"
    fi

    inject_block "$rc_file" "$env_file"
    local_perms
    perms=$(stat -c '%a' "$env_file" 2>/dev/null || stat -f '%Lp' "$env_file" 2>/dev/null)
    log "Source block injetado em $rc_file"
    log "Env file: $env_file (perm $perms)"
    echo ""
    info "Para ativar agora: source $rc_file"
    info "Novos terminais carregarão as vars automaticamente."
    info "Para inspecionar: bash scripts/persist-env.sh --show"
    ;;
esac
